import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { Sparkles, RefreshCw, Brain, Target } from 'lucide-react';
import CollegeCard from '@/components/cards/CollegeCard';
import { CollegeCardSkeleton } from '@/components/loaders/Skeleton';
import { recommendationService } from '@/services/api/recommendationService';
import { useAuthStore } from '@/context/authStore';
import { Link } from 'react-router-dom';

export default function RecommendationsPage() {
  const { user } = useAuthStore();
  const [recommendations, setRecommendations] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchRecs = async () => {
    setLoading(true);
    try { const d = await recommendationService.getPersonalized(user?.id || ''); setRecommendations(d); }
    catch { setRecommendations([]); }
    finally { setLoading(false); }
  };

  useEffect(() => { fetchRecs(); }, []);

  return (
    <div className="space-y-6 max-w-7xl">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div>
          <h1 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white font-display">AI Recommendations</h1>
          <p className="text-gray-500 dark:text-gray-400 mt-1 text-sm">Personalized college matches based on your profile and preferences</p>
        </div>
        <button
          onClick={fetchRecs}
          disabled={loading}
          className="flex items-center gap-2 px-4 py-2.5 rounded-xl border border-gray-200 dark:border-[#1c1c35] text-sm font-medium text-gray-700 dark:text-gray-300 hover:border-[#6b5fff]/40 hover:text-[#6b5fff] transition-all disabled:opacity-50"
        >
          <RefreshCw size={15} className={loading ? 'animate-spin' : ''} /> Refresh
        </button>
      </div>

      {/* AI banner */}
      <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="p-5 rounded-2xl bg-gradient-to-r from-[#6b5fff]/8 to-[#a855f7]/6 border border-[#6b5fff]/15">
        <div className="flex items-start gap-4">
          <div className="w-11 h-11 rounded-xl bg-gradient-to-br from-[#6b5fff] to-[#8b5cf6] flex items-center justify-center flex-shrink-0 shadow-md shadow-[#6b5fff]/25">
            <Brain className="w-5 h-5 text-white" />
          </div>
          <div>
            <h3 className="font-semibold text-gray-900 dark:text-white mb-1">Powered by Gemini AI</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400 leading-relaxed">
              These recommendations are generated by analyzing your academic interests, budget, location preferences, and career goals.
              Each college is scored on how well it matches your unique profile.
            </p>
            <Link to="/questionnaire" className="inline-flex items-center gap-1.5 mt-3 text-sm font-semibold text-[#6b5fff] dark:text-[#a89fff] hover:underline">
              <Target size={14} /> Retake questionnaire for better matches
            </Link>
          </div>
        </div>
      </motion.div>

      {loading ? (
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">
          {Array.from({ length: 6 }).map((_, i) => <CollegeCardSkeleton key={i} />)}
        </div>
      ) : recommendations.length === 0 ? (
        <div className="text-center py-16">
          <div className="w-16 h-16 rounded-2xl bg-[#6b5fff]/8 flex items-center justify-center mx-auto mb-4">
            <Sparkles className="w-8 h-8 text-[#6b5fff]" />
          </div>
          <p className="text-gray-900 dark:text-white font-semibold mb-2">No recommendations yet</p>
          <p className="text-sm text-gray-500 dark:text-gray-400 mb-5">Complete your profile and questionnaire to get personalised suggestions.</p>
          <Link to="/questionnaire">
            <button className="px-5 py-2.5 rounded-xl bg-gradient-to-r from-[#6b5fff] to-[#8b5cf6] text-white text-sm font-semibold shadow-md shadow-[#6b5fff]/20">
              Start Questionnaire
            </button>
          </Link>
        </div>
      ) : (
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">
          {recommendations.map((college, i) => (
            <div key={college.id} className="relative">
              <CollegeCard college={college} index={i} matchScore={college.matchScore} />
              {college.reason && (
                <p className="mt-2 px-2 text-xs text-gray-500 dark:text-gray-400 leading-relaxed">{college.reason}</p>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
